
//login
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

//Registration
export const REGISTRATION_USER_REQUEST = "SIGNIN_USER_REQUEST";
export const REGISTRATION_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const REGISTRATION_USER_ERROR = "SIGNIN_USER_ERROR";

//get registation data
export const GET_REGISTRATION_DATA_REQUEST = " GET_REGISTRATION_DATA_REQUEST";
export const GET_REGISTRATION_DATA_SUCCESS = "GET_REGISTRATION_DATA_SUCCESS";
export const GET_REGISTRATION_DATA_ERROR = "GET_REGISTRATION_DATA_ERROR";

//SurveyData
export const GET_SURVEY_DATA_REQUEST = "GET_SURVEY_DATA_REQUEST";
export const GET_SURVEY_DATA_SUCCESS = "GET_SURVEY_DATA_SUCCESS";
export const GET_SURVEY_DATA_ERROR = "GET_SURVEY_DATA_ERROR";

//SurevyDataPost
export const POST_SURVEY_DATA_REQUEST = "POST_SURVEY_DATA_REQUEST";
export const POST_SURVEY_DATA_SUCCESS = "POST_SURVEY_DATA_SUCCESS";
export const POST_SURVEY_DATA_ERROR = "POST_SURVEY_DATA_ERROR";

// fetch survey data
export const FETCH_SURVEY_DATA_REQUEST = " FFETCH_SURVEY_DATA_REQUEST";
export const FETCH_SURVEY_DATA = "FETCH_SURVEY_DATA";
export const FETCH_SURVEY_DATA_ERROR = "FETCH_SURVEY_DATA_ERROR";

//worker data

//SurveyWorkerData
export const GET_WORKER_DATA_REQUEST = "GET_WORKER_DATA_REQUEST";
export const GET_WORKER_DATA_SUCCESS = "GET_WORKER_DATA_SUCCESS";
export const GET_WORKER_DATA_ERROR = "GET_WORKER_DATA_ERROR";

//SurevyWorkerDataPost
export const POST_WORKER_DATA_REQUEST = "POST_WORKER_DATA_REQUEST";
export const POST_WORKER_DATA_SUCCESS = "POST_WORKER_DATA_SUCCESS";
export const POST_WORKER_DATA_ERROR = "POST_WORKER_DATA_ERROR";

// fetch worker data
export const FETCH_WORKER_DATA_REQUEST = " FFETCH_WORKER_DATA_REQUEST";
export const FETCH_WORKER_DATA = "FETCH_WORKER_DATA";
export const FETCH_WORKER_DATA_ERROR = "FETCH_WORKER_DATA_ERROR";

// editUserData
export const Edit_USER_DATA = " Edit_USER_DATA";

//userEditDataPost
export const POST_EDIT_USER_DATA_REQUEST = "POST_USER_EDIT_DATA_REQUEST";
export const POST_EDIT_USER_DATA_SUCCESS = "POST_USER_EDIT_DATA_SUCCESS";
export const POST_EDIT_USER_DATA_ERROR = "POST_SUSER_EDIT_DATA_ERROR";

// delete user
export const DELETE_USER_DATA_REQUEST = "DELETE_USER_DATA_REQUEST";
export const DELETE_USER_DATA_SUCCESS = "DELETE_USER_DATA_SUCCESS";
export const DELETE_USER_DATA_ERROR = "DELETE_USER_DATA_ERROR";