export const SURVEY_DATA = "SURVEY_DATA";
export const USER_SIGN_IN = "USER_SIGN_IN";
export const TOGGLE = "TOGGLE";
//login
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

//SignIn
export const SIGNIN_USER_REQUEST = "SIGNIN_USER_REQUEST";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_ERROR = "SIGNIN_USER_ERROR";

//SurveyData
export const GET_SURVEY_DATA_REQUEST = "GET_SURVEY_DATA_REQUEST";
export const GET_SURVEY_DATA_SUCCESS = "GET_SURVEY_DATA_SUCCESS";
export const GET_SURVEY_DATA_ERROR = "GET_SURVEY_DATA_ERROR";

//SurevyDataPost
export const POST_SURVEY_DATA_REQUEST = "POST_SURVEY_DATA_REQUEST";
export const POST_SURVEY_DATA_SUCCESS = "POST_SURVEY_DATA_SUCCESS";
export const POST_SURVEY_DATA_ERROR = "POST_SURVEY_DATA_ERROR";

// fetch survey data
export const FETCH_SURVEY_DATA_REQUEST = " FFETCH_SURVEY_DATA_REQUEST";
export const FETCH_SURVEY_DATA = "FETCH_SURVEY_DATA";
export const FETCH_SURVEY_DATA_ERROR = "FETCH_SURVEY_DATA_ERROR";
